 USE MASTER 
 IF EXISTS (SELECT* FROM SYS.DATABASES WHERE NAME = 'QLSV')
	DROP DATABASE QLSV
GO
	CREATE DATABASE QLSV
USE QLSV
GO
-- CREATE TABLE 
IF EXISTS (SELECT* FROM SYS.objects WHERE NAME = 'LOP')
	DROP TABLE LOP
GO
CREATE TABLE LOP
(
	MALOP CHAR(7) NOT NULL,
	TENLOP NVARCHAR(50) NOT NULL,
	SISO TINYINT CHECK(SISO>0)
)
IF EXISTS (SELECT* FROM SYS.objects WHERE NAME = 'MONHOC')
	DROP TABLE MONHOC
GO
CREATE TABLE MONHOC
(
	MAMH CHAR(6) NOT NULL,
	TENMH NVARCHAR(50) NOT NULL,
	TCLT TINYINT CHECK(TCLT>0),
	TCTH TINYINT CHECK(TCTH>0)
)
IF EXISTS(SELECT* FROM SYS.objects WHERE NAME = 'SINHVIEN')
	DROP TABLE SINHVIEN
GO
CREATE TABLE SINHVIEN
(
	MSSV CHAR(5) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	NTNS DATE NOT NULL,
	MALOP CHAR(7) NOT NULL,
)
IF EXISTS(SELECT*FROM SYS.objects where name = 'DIEMSV')
	DROP TABLE DIEMSV
GO
CREATE TABLE DIEMSV
(
	MSSV CHAR(5) NOT NULL,
	MAMH CHAR(6) NOT NULL,
	DIEM DECIMAL(3,1)
)
-- CREATE PRIMARY KEY 
ALTER TABLE LOP ADD CONSTRAINT PK_MALOP PRIMARY KEY(MALOP)
ALTER TABLE MONHOC ADD CONSTRAINT PK_MAMH PRIMARY KEY(MAMH)
ALTER TABLE SINHVIEN ADD CONSTRAINT PK_MSSV PRIMARY KEY(MSSV)
ALTER TABLE DIEMSV ADD CONSTRAINT PK_DIEMSV PRIMARY KEY(MASV,MAMH)

--CREATE FORIEN KEY 
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_MALOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)

ALTER TABLE DIEMSV ADD CONSTRAINT FK_MSSV FOREIGN KEY(MSSV) REFERENCES SINHVIEN(MSSV),
  CONSTRAINT FK_MAMH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)

INSERT INTO LOP(MALOP,TENLOP,SISO) VALUES ('18DTH01','CNTT Khóa 18, Lớp 1',50)

INSERT INTO LOP(MALOP,TENLOP,SISO)VALUES ('18DTH02','CNTT Khóa 18 Lớp 2',45)

INSERT INTO LOP(MALOP,TENLOP,SISO) VALUES ('19DTH01','CNTT Khóa 19 Lớp 1',55)

INSERT INTO LOP(MALOP,TENLOP,SISO) VALUES ('19DTH02','CNTT Khóa 19, Lớp 2',50)

INSERT INTO LOP(MALOP,TENLOP,SISO) VALUES ('19DTH03	','CNTT Khóa 19, Lớp 3',40)

INSERT INTO MONHOC(MAMH,TENMH,TCLT,TCTH) VALUES ('COS201'	,'Kỹ thuật lập trình',	2	,1)
INSERT INTO MONHOC(MAMH,TENMH,TCLT,TCTH) VALUES ('18DTH01','CNTT Khóa 18, Lớp 1',50)
INSERT INTO MONHOC(MAMH,TENMH,TCLT,TCTH) VALUES ('18DTH01','CNTT Khóa 18, Lớp 1',50)
INSERT INTO MONHOC(MAMH,TENMH,TCLT,TCTH) VALUES ('18DTH01','CNTT Khóa 18, Lớp 1',50)
INSERT INTO MONHOC(MAMH,TENMH,TCLT,TCTH) VALUES ('18DTH01','CNTT Khóa 18, Lớp 1',50)


'COS203'	,'CSDLvà quản trị CSDL',	3,	0
'COS204'	,'Phân tích thiết kế hệ thống',	3,	0
'COS205'	,'CSDL phân tán',	3,	0
