use MASTER
if EXISTS (SELECT*FROM SYS.DATABASES where NAME = 'QLKH')
    DROP DATABASE QLKH
GO
CREATE DATABASE QLKH
USE QLKH
IF EXISTS (SELECT*FROM SYS.objects WHERE NAME = 'KHACHHANG')
    DROP TABLE  KHACHHANG
GO 
CREATE TABLE KHACHHANG
(
    MAKHACHHANG  NVARCHAR(10) NOT NULL ,
    TENCONGTY NVARCHAR(15) NOT NULL,
    TENGIAODICH NVARCHAR(20) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(40) NOT NULL,
    DIENTHOAI TINYINT,
    FAX NVARCHAR(10) ,
    PRIMARY KEY(MAKHACHHANG)
)
IF EXISTS(SELECT*FROM SYS.objects WHERE NAME = 'DONDATHANG')
    DROP TABLE DONDATHANG
GO
CREATE TABLE DONDATHANG
(
    SOHOADON INT,
    MAKHACHHANG NVARCHAR(10) NOT NULL,
    MANHANVIEN NVARCHAR(10) NOT NULL,
    NGAYDATHANG DATE,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAODICH NVARCHAR(100) NOT NULL,
    PRIMARY KEY(SOHOADON),
    CONSTRAINTS FK_MAKHACHHANG FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
    CONSTRAINTS FK_NHANVIEN FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
)
IF EXISTS(SELECT*FROM SYS.objects WHERE NAME = 'NHANVIEN')
    DROP TABLE NHANVIEN
GO
CREATE TABLE NHANVIEN
(
    MANHANVIEN NVARCHAR(10) NOT NULL,
    HO NVARCHAR(12) NOT NULL,
    TEN NVARCHAR(12) NOT NULL,
    NGAYSINH DATE,
    NGAYLAMVIEC DATE,
    DIACHI NVARCHAR(100) NOT NULL,
    DIENTHOAI TINYINT,
    LUONGCOBAN INT,
    PRIMARY KEY(MANHANVIEN)
)

IF EXISTS(SELECT*FROM SYS.objects WHERE NAME = 'NHACUNGCAP')
    DROP TABLE NHACUNGCAP
GO
CREATE TABLE NHACUNGCAP
(
    MACONGTY NVARCHAR(10) NOT NULL,
    TENCONGTY  NVARCHAR(15) NOT NULL,
    TENGIAODICH NVARCHAR(20) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    DIENTHOAI TINYINT ,
    FAX NVARCHAR(10) ,
    EMAIL NVARCHAR(40) NOT NULL,
    PRIMARY KEY(MACONGTY) 
)
IF EXISTS(SELECT*FROM SYS.objects WHERE NAME = 'CHITIETDATHANG')
    DROP TABLE CHITIETDATHANG
GO
CREATE TABLE CHITIETDATHANG
(
    SOHOADON INT,
    MAHANG NVARCHAR(20) NOT NULL,
    GIABAN FLOAT,
    SOLUONG INT,
    MUCGIAMGIA FLOAT,
    PRIMARY KEY(SOHOADON,MAHANG),
    CONSTRAINTS FK_SOHOADON FOREIGN KEY(SOHOADON) REFERENCES DONDATHANG(SOHOADON),
    CONSTRAINTS FK_MAHANG FOREIGN KEY(MAHANG) REFERENCES MATHANG(MAHANG),
    
)
IF EXISTS(SELECT*FROM SYS.objects WHERE NAME = 'MATHANG')
    DROP TABLE MATHANG
GO
CREATE TABLE MATHANG
(
    MAHANG NVARCHAR(20) NOT NULL,
    TENHANG NVARCHAR(50) NOT NULL,
    MACONGTY NVARCHAR(10) NOT NULL,
    MALOAIHANG NVARCHAR(10) NOT NULL,
    SOLUONG INT,
    DONVITING CHAR,
    GIAHANG INT,
    PRIMARY KEY(MAHANG),
    CONSTRAINTS FK_MACONGTY FOREIGN KEY(MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
    CONSTRAINTS FK_MALOAIHANG FOREIGN KEY(MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
)
IF EXISTS(SELECT*FROM SYS.objects WHERE NAME = 'LOAIHANG')
    DROP TABLE LOAIHANG
GO
CREATE TABLE LOAIHANG
(
    MALOAIHANG NVARCHAR(10) NOT NULL,
    TENLOAIHANG NVARCHAR(20) NOT NULL,
    PRIMARY KEY(MALOAIHANG)
)

--CREATE KEY
